server:
  port: 9100
spring:
  application:
    name: fileUpload-service
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.216.156:3306/PhoneMark?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: Asd8711341

mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.gsn.pm: debug

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 90 # 10秒不发送就过期