server:
  port: 8130


spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/resources/static #重启目录
      #exclude:
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Asd8711341
    url: jdbc:mysql://1.15.83.26:3306/PhoneMark?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  cloud:    ##FeignClient超时设置
    loadbalancer.retry.enabled: true
    stream:
      kafka:
        binder:
          brokers: 121.5.167.32
  application:
    name: pm-web


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
ribbon.ConnectTimeout: 60000
ribbon.ReadTimeout: 60000
ribbon.OkToRetryOnAllOperations: true
ribbon.MaxAutoRetriesNextServer: 2
ribbon.MaxAutoRetries: 1




#服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:a@eureka1:7301/eureka
  register-with-eureka: false   #自己不注册到eureka中，只做eureka的客户端，读取服务
  instance:     #实例配置, 没有在eureka注册，所以有没有都没关系
    preferIpAddress: true
    instance-id: pic-web_1
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30


#这里将所有的监控端口打开
management:
  endpoints:
    web:
      exposure:
        include: '*'




---
#spring devtools 更改类程序文件不使用热部署自动重启
spring.devtools.restart.enabled: false
spring.devtools.livereload.enabled: false